import { Practice } from '../types/practice';

// Mock practices data - 29 Práticas Integrativas do SUS em ordem alfabética
const mockPractices: Practice[] = [
  {
    id: '1',
    name: 'Acupuntura',
    definition: 'A Acupuntura é uma técnica terapêutica milenar da Medicina Tradicional Chinesa que consiste na aplicação de agulhas muito finas em pontos específicos do corpo, chamados de acupontos. Esta prática visa promover o equilíbrio energético do organismo através da estimulação do fluxo de energia vital (Qi), que circula por canais energéticos denominados meridianos. Segundo a filosofia chinesa, quando há bloqueios ou desequilíbrios no fluxo do Qi, surgem doenças e sintomas diversos. A acupuntura atua desbloqueando esses canais e restaurando o fluxo energético natural. É uma das práticas integrativas mais conhecidas e utilizadas no mundo, reconhecida pela Organização Mundial da Saúde como eficaz para diversas condições de saúde. No SUS, a acupuntura é oferecida gratuitamente como parte das Práticas Integrativas e Complementares, proporcionando uma abordagem natural e holística para o tratamento de diversas condições. A técnica é baseada em um sistema diagnóstico próprio que considera não apenas os sintomas, mas também a constituição energética individual do paciente.',
    origin: 'Originária da China antiga, com mais de 2.500 anos de história documentada nos textos clássicos como o "Huangdi Neijing" (Clássico de Medicina Interna do Imperador Amarelo). Desenvolveu-se ao longo dos séculos através da observação empírica e sistematização de conhecimentos sobre os pontos energéticos do corpo humano. A prática se espalhou por toda a Ásia e posteriormente para o Ocidente. Chegou ao Brasil na década de 1950 através da imigração chinesa e japonesa, ganhando reconhecimento científico gradualmente. Foi oficialmente incluída no Sistema Único de Saúde em 2006 através da Política Nacional de Práticas Integrativas e Complementares. Atualmente é praticada em diversos países e integrada a sistemas de saúde públicos e privados ao redor do mundo.',
    application: 'O tratamento é realizado por profissionais capacitados (médicos, fisioterapeutas, enfermeiros, dentistas) que inserem agulhas estéreis e descartáveis em pontos específicos do corpo, seguindo protocolos de segurança rigorosos. As sessões duram entre 20 a 40 minutos, e o número de sessões varia conforme a condição tratada, geralmente entre 6 a 12 sessões. O paciente permanece em posição confortável durante o procedimento, que é praticamente indolor. Pode ser combinada com outras técnicas como moxabustão (aquecimento dos pontos), ventosaterapia (aplicação de ventosas), eletroacupuntura (estimulação elétrica das agulhas) e auriculoterapia. O tratamento é personalizado conforme o diagnóstico energético individual, considerando o padrão de desequilíbrio específico de cada pessoa.',
    indications: 'Dores crônicas e agudas (artrite, artrose, fibromialgia, dores nas costas, cervicalgia), enxaqueca e cefaleia tensional, ansiedade e transtornos do humor, depressão leve a moderada, insônia e distúrbios do sono, problemas digestivos (gastrite, síndrome do intestino irritável, constipação), hipertensão arterial leve, síndrome do túnel do carpo e tendinites, náuseas e vômitos (incluindo quimioterapia), dependência química (tabagismo, alcoolismo), problemas respiratórios (asma, rinite alérgica), distúrbios neurológicos (paralisia facial, sequelas de AVC), problemas ginecológicos (TPM, irregularidades menstruais), e condições dermatológicas (eczema, acne). Também é eficaz para fortalecimento do sistema imunológico e melhora da qualidade de vida em geral.',
    benefits: 'Alívio eficaz e duradouro de dores crônicas e agudas, redução significativa do estresse e ansiedade através da liberação de endorfinas naturais, melhora substancial da qualidade do sono e regulação dos ciclos circadianos, equilíbrio emocional e estabilização do humor, fortalecimento do sistema imunológico e aumento da resistência a infecções, redução da necessidade de medicamentos analgésicos e anti-inflamatórios, melhora da circulação sanguínea e linfática, regulação hormonal natural, aumento da energia vital e disposição, melhora da concentração e clareza mental, e promoção do bem-estar geral. Os efeitos são cumulativos e tendem a se manter por períodos prolongados após o término do tratamento.',
    contraindications: 'Hemofilia e outros distúrbios graves de coagulação sanguínea, uso de anticoagulantes em doses altas (requer avaliação médica), fobia severa de agulhas que impeça a realização do tratamento, gravidez de alto risco (alguns pontos específicos são contraindicados), infecções locais na pele ou lesões abertas nos locais de aplicação, estado febril agudo ou infecções sistêmicas graves, pacientes com marcapasso cardíaco (contraindicação específica para eletroacupuntura), imunodeficiência severa, transtornos psiquiátricos graves em fase aguda, e crianças muito pequenas que não conseguem permanecer imóveis durante o procedimento. Em casos de diabetes, é necessário cuidado especial com a cicatrização.',
    imageUrl: 'https://images.pexels.com/photos/5473298/pexels-photo-5473298.jpeg',
  },
  {
    id: '2',
    name: 'Antroposofia Aplicada à Saúde',
    definition: 'A Antroposofia Aplicada à Saúde é uma abordagem médica integrativa desenvolvida por Rudolf Steiner que considera o ser humano em suas dimensões física, vital, psíquica e espiritual, baseada na compreensão de que o indivíduo possui quatro corpos constituintes: físico, etérico, astral e eu superior. Esta prática busca compreender o indivíduo de forma integral, utilizando medicamentos antroposóficos preparados segundo métodos específicos, terapias artísticas, euritmia curativa, massagens rítmicas e outras modalidades terapêuticas. O diagnóstico antroposófico considera não apenas os sintomas físicos, mas também os aspectos biográficos, constitucionais e os ritmos vitais da pessoa. O tratamento é personalizado e leva em conta a constituição individual, o temperamento, o momento de vida e os processos de desenvolvimento pessoal. É uma medicina que dialoga respeitosamente com a medicina convencional, complementando-a com uma visão ampliada e humanizada do processo saúde-doença, sempre priorizando o despertar das forças autocurativas do organismo.',
    origin: 'Desenvolvida no início do século XX (1920-1925) pelo filósofo, educador e cientista austríaco Rudolf Steiner, em colaboração com médicos como Ita Wegman e outros pioneiros da medicina antroposófica. Surgiu como uma extensão da antroposofia, ciência espiritual que busca compreender o ser humano e o cosmos de forma integral. A medicina antroposófica se desenvolveu inicialmente na Europa, especialmente na Alemanha e Suíça, onde foram fundadas as primeiras clínicas e farmácias especializadas. Chegou ao Brasil na década de 1950 através de médicos e terapeutas europeus, estabelecendo-se gradualmente em várias regiões do país. Foi oficialmente incluída na Política Nacional de Práticas Integrativas e Complementares (PNPIC) em 2006, sendo reconhecida como uma das práticas integrativas do Sistema Único de Saúde.',
    application: 'O tratamento inclui consultas médicas especializadas com anamnese biográfica detalhada, exame físico diferenciado e diagnóstico antroposófico, prescrição de medicamentos antroposóficos preparados através de processos de dinamização e potencialização, terapias artísticas específicas (pintura terapêutica, modelagem, música, fala), euritmia curativa (movimento terapêutico baseado nas forças formativas da linguagem), massagem rítmica segundo Ita Wegman, quirofonética (trabalho com sons e movimento), e orientações detalhadas sobre alimentação biodinâmica, ritmos de vida e autocuidado. O médico antroposófico considera cuidadosamente a biografia do paciente, sua individualidade constitucional, os ciclos de desenvolvimento (setênios) e os aspectos psicossociais que influenciam o processo de adoecimento e cura.',
    indications: 'Doenças crônicas complexas que requerem abordagem integrativa, transtornos do desenvolvimento infantil (TDAH, autismo, dificuldades de aprendizagem), problemas emocionais e comportamentais em todas as idades, doenças autoimunes (artrite reumatoide, esclerose múltipla, lúpus), câncer como terapia complementar ao tratamento convencional, distúrbios do sono e ritmos biológicos, ansiedade e depressão especialmente relacionadas a crises existenciais, transtornos alimentares, problemas dermatológicos crônicos, distúrbios digestivos funcionais, síndrome de burnout e esgotamento vital, problemas ginecológicos e da sexualidade, e condições que requerem uma abordagem preventiva e de fortalecimento da vitalidade. Também é indicada para pessoas que buscam um desenvolvimento pessoal mais consciente e integrado.',
    benefits: 'Tratamento verdadeiramente individualizado e humanizado que considera a pessoa em sua totalidade, fortalecimento significativo da capacidade de autorregulação e autocura do organismo, melhora substancial da qualidade de vida e vitalidade geral, redução considerável de efeitos colaterais de tratamentos convencionais quando usada complementarmente, desenvolvimento da consciência corporal, emocional e espiritual, promoção do equilíbrio integral entre corpo, alma e espírito, estímulo à criatividade e capacidades artísticas como fatores terapêuticos, fortalecimento da resiliência e capacidade de enfrentamento de crises, desenvolvimento de maior autonomia e responsabilidade no processo de cura, e promoção de um envelhecimento mais saudável e consciente. Os medicamentos antroposóficos geralmente não apresentam efeitos colaterais significativos e podem ser usados por períodos prolongados.',
    contraindications: 'Não substitui tratamentos médicos convencionais em emergências médicas, doenças agudas graves que requerem intervenção imediata, ou condições que necessitam de cirurgia urgente. Deve ser praticada exclusivamente por profissionais devidamente qualificados em medicina antroposófica com formação reconhecida. Alguns medicamentos antroposóficos podem ter contraindicações específicas em casos de alergias conhecidas aos componentes. Em casos de transtornos psiquiátricos graves, deve ser usada como complemento ao tratamento psiquiátrico convencional, nunca como substituto. Pacientes com doenças terminais devem receber acompanhamento médico convencional paralelo. É importante que o paciente tenha abertura e receptividade à abordagem antroposófica para que o tratamento seja eficaz.',
    imageUrl: 'https://images.pexels.com/photos/6823568/pexels-photo-6823568.jpeg',
  },
  {
    id: '3',
    name: 'Apiterapia',
    definition: 'A Apiterapia é uma prática terapêutica ancestral que utiliza de forma sistemática e científica os produtos das abelhas como mel, própolis, pólen, geleia real, cera de abelha e apitoxina (veneno da abelha) para fins medicinais e de promoção da saúde. Esta terapia milenar aproveita as propriedades antimicrobianas, anti-inflamatórias, antioxidantes, imunomoduladoras, cicatrizantes e analgésicas desses produtos naturais únicos. A apitoxina, em particular, contém mais de 40 substâncias bioativas e é utilizada em tratamentos específicos para condições inflamatórias, autoimunes e neurológicas. É uma prática que combina conhecimentos tradicionais milenares com evidências científicas modernas, oferecendo uma abordagem natural, sustentável e eficaz para diversos problemas de saúde. No SUS, a apiterapia foi incluída em 2018 como uma das práticas integrativas reconhecidas, ampliando o acesso da população a essa terapia natural.',
    origin: 'Prática milenar utilizada por diversas civilizações antigas há mais de 4.000 anos, incluindo egípcios (que usavam mel para embalsamamento e cura), gregos antigos (Hipócrates prescrevia mel para diversas condições), chineses (medicina tradicional chinesa incorpora produtos apícolas), e povos indígenas de várias culturas. Foi sistematizada cientificamente no século XX por pesquisadores como Philip Terc na Áustria e Bodog Beck nos Estados Unidos, que documentaram os efeitos terapêuticos da apitoxina. A prática moderna se desenvolveu especialmente na Europa Oriental e Rússia, onde há centros especializados. No Brasil, chegou através de imigrantes europeus e foi gradualmente incorporada às práticas integrativas. Foi oficialmente incluída no Sistema Único de Saúde em 2018, reconhecendo sua eficácia e segurança quando praticada adequadamente.',
    application: 'Os produtos apícolas podem ser utilizados através de diferentes vias: via oral (mel puro, própolis em gotas ou cápsulas, pólen de abelha, geleia real), aplicação tópica (pomadas, cremes, unguentos à base de própolis, cera e mel), inalação (própolis vaporizado para problemas respiratórios), e aplicação controlada de apitoxina através de picadas de abelhas vivas em pontos específicos ou injeções subcutâneas de veneno purificado. O tratamento com apitoxina requer protocolo específico com teste de sensibilidade inicial, aplicação gradual e monitoramento constante. Todos os tratamentos devem ser sempre supervisionados por profissionais capacitados e certificados em apiterapia, seguindo protocolos de segurança rigorosos.',
    indications: 'Artrite reumatoide e artrose com processo inflamatório, fibromialgia e síndromes dolorosas crônicas, esclerose múltipla e outras doenças desmielinizantes, doenças autoimunes (lúpus, psoríase, artrite psoriásica), feridas crônicas e úlceras de difícil cicatrização, problemas respiratórios (asma, bronquite, sinusite), infecções bacterianas, virais e fúngicas resistentes, baixa imunidade e infecções recorrentes, fadiga crônica e síndrome de burnout, problemas dermatológicos (eczema, dermatite, acne), condições inflamatórias do sistema digestivo, neuropatias periféricas, e como adjuvante em tratamentos oncológicos. Também é eficaz para fortalecimento geral do organismo e prevenção de doenças.',
    benefits: 'Potente ação anti-inflamatória e analgésica natural sem efeitos colaterais significativos, fortalecimento robusto do sistema imunológico e aumento da resistência a infecções, propriedades antimicrobianas de amplo espectro contra bactérias, vírus e fungos, poderosa ação antioxidante que combate o envelhecimento celular, melhora significativa da cicatrização e regeneração tecidual, aumento substancial da energia, vitalidade e disposição física, redução considerável de sintomas de doenças autoimunes e inflamatórias crônicas, melhora da qualidade do sono e redução do estresse, regulação hormonal natural, e promoção da longevidade e qualidade de vida. Os produtos apícolas são ricos em vitaminas, minerais, aminoácidos e enzimas essenciais para o organismo.',
    contraindications: 'Alergia conhecida a qualquer produto apícola (requer teste de sensibilidade obrigatório antes do tratamento), gravidez e período de lactação (especialmente para apitoxina), crianças menores de 2 anos para consumo de mel (risco de botulismo infantil), doenças cardíacas graves e arritmias severas, insuficiência renal ou hepática em estágio avançado, uso de anticoagulantes potentes (para tratamento com apitoxina), asma severa não controlada, transtornos de coagulação hereditários, imunodeficiência severa, e diabetes descompensado (cuidado especial com mel). Pacientes com múltiplas alergias devem ser avaliados criteriosamente antes do início do tratamento.',
    imageUrl: 'https://images.pexels.com/photos/4022090/pexels-photo-4022090.jpeg',
  },
  {
    id: '4',
    name: 'Aromaterapia',
    definition: 'A Aromaterapia é uma prática terapêutica holística e científica que utiliza óleos essenciais puros extraídos de plantas aromáticas medicinais para promover, restaurar e manter o bem-estar físico, mental, emocional e espiritual. Estes concentrados voláteis altamente potentes contêm as essências bioativas das plantas e possuem propriedades terapêuticas específicas como compostos terpênicos, ésteres, aldeídos e fenóis que podem ser absorvidas através da inalação, aplicação tópica diluída ou difusão ambiental. A aromaterapia atua diretamente no sistema límbico do cérebro através do sistema olfativo, responsável pelas emoções, memórias e funções autonômicas, proporcionando efeitos relaxantes, energizantes, anti-inflamatórios, antimicrobianos, analgésicos ou equilibrantes conforme o óleo utilizado. É uma prática suave, natural e baseada em evidências que pode ser facilmente integrada ao cotidiano e aos tratamentos convencionais, oferecendo uma abordagem holística, personalizada e eficaz para o cuidado integral da saúde.',
    origin: 'Utilizada há mais de 5.000 anos por diversas civilizações antigas como egípcios (que usavam óleos aromáticos em rituais religiosos, medicina e mumificação), gregos antigos (Hipócrates prescrevia fumigações aromáticas), romanos (banhos aromáticos terapêuticos), chineses e indianos através da medicina ayurvédica. O termo moderno "aromaterapia" foi criado pelo químico e perfumista francês René-Maurice Gattefossé em 1928, após descobrir acidentalmente as propriedades cicatrizantes do óleo de lavanda. A prática foi sistematizada cientificamente por Jean Valnet, Marguerite Maury e outros pesquisadores europeus. No Brasil, foi oficialmente incluída na Política Nacional de Práticas Integrativas e Complementares do SUS em 2006, sendo uma das primeiras práticas reconhecidas pelo sistema público de saúde.',
    application: 'Os óleos essenciais podem ser utilizados através de múltiplas técnicas seguras e eficazes: difusão no ambiente através de difusores ultrassônicos, elétricos ou por calor, inalação direta (algumas gotas em lenço ou palmas das mãos), massagem terapêutica com óleos sempre diluídos em óleos vegetais carreadores (coco, jojoba, amêndoas), banhos aromáticos relaxantes ou estimulantes, compressas quentes ou frias para dores localizadas, sprays ambientais naturais, e aplicação tópica localizada sempre respeitando as diluições adequadas. Cada método de aplicação oferece benefícios específicos conforme a necessidade terapêutica individual, faixa etária e condição de saúde. É fundamental utilizar óleos 100% puros, naturais e de qualidade terapêutica comprovada.',
    indications: 'Transtornos de ansiedade e síndrome do pânico, estresse crônico e síndrome de burnout, insônia e outros distúrbios do sono, depressão leve a moderada e distúrbios do humor, enxaquecas e dores de cabeça tensionais, problemas respiratórios (asma, bronquite, sinusite, gripes e resfriados), tensão muscular, dores articulares e fibromialgia, fadiga crônica e baixa energia, baixa concentração e problemas de memória, problemas dermatológicos (acne, eczema, cicatrização), desequilíbrios emocionais e traumas, sintomas da menopausa e TPM, problemas digestivos (náuseas, indigestão), baixa imunidade e infecções recorrentes, e como coadjuvante em tratamentos oncológicos para alívio de efeitos colaterais da quimioterapia e radioterapia.',
    benefits: 'Redução significativa do estresse, ansiedade e tensão emocional através da modulação do sistema nervoso, melhora substancial da qualidade e profundidade do sono, alívio eficaz de dores musculares, articulares e dores de cabeça, fortalecimento natural do sistema imunológico e aumento da resistência a infecções, melhora considerável do humor, concentração e clareza mental, propriedades antimicrobianas, antivirais e antifúngicas de amplo espectro, efeitos anti-inflamatórios e analgésicos naturais, promoção de relaxamento profundo e renovação energética, regulação hormonal natural e equilíbrio emocional, melhora da circulação sanguínea e linfática, efeitos antioxidantes que combatem o envelhecimento celular, e harmonização dos centros energéticos promovendo bem-estar integral.',
    contraindications: 'Alergia conhecida a óleos essenciais específicos (requer teste de sensibilidade cutânea antes do uso), gravidez e lactação (muitos óleos são contraindicados, especialmente no primeiro trimestre), epilepsia e convulsões (óleos estimulantes como alecrim, eucalipto e cânfora), asma severa não controlada (alguns óleos podem desencadear crises), crianças menores de 3 anos (a maioria dos óleos essenciais), hipertensão arterial severa, aplicação pura na pele sem diluição adequada (risco de queimaduras e sensibilização), exposição solar após uso de óleos fotossensibilizantes (bergamota, limão, laranja), uso interno sem supervisão de aromaterapeuta qualificado, e interação com medicamentos específicos (anticoagulantes, sedativos). Pacientes com múltiplas sensibilidades químicas devem ser avaliados cuidadosamente.',
    imageUrl: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  },
  {
    id: '5',
    name: 'Reiki',
    definition: 'O Reiki é uma técnica japonesa ancestral de canalização e transmissão de energia vital universal para promover relaxamento profundo, redução do estresse e facilitar os processos naturais de cura e autorregulação do organismo. A palavra "Reiki" significa literalmente "energia vital universal" em japonês (Rei = energia universal/espiritual, Ki = energia vital/força da vida) e baseia-se no princípio fundamental de que existe uma força vital inteligente que flui através de todos os seres vivos e permeia todo o universo. Quando essa energia está baixa, bloqueada ou desequilibrada, somos mais propensos a desenvolver doenças físicas, emocionais ou mentais, além de experimentar estresse e mal-estar. O Reiki é aplicado através da imposição suave das mãos sobre pontos específicos do corpo do receptor, permitindo que o praticante atue como um canal para a energia universal curativa, que promove o reequilíbrio e a harmonização dos centros energéticos (chakras) e dos sistemas físico, mental, emocional e espiritual. É uma prática completamente suave, não invasiva, segura e complementar que pode ser utilizada eficazmente junto com outros tratamentos médicos convencionais e terapias integrativas.',
    origin: 'Desenvolvido no Japão no início do século XX (1922) pelo monge budista e professor Mikao Usui, após uma experiência espiritual de 21 dias de jejum e meditação no Monte Kurama. Usui baseou-se em antigas práticas de cura tibetanas, japonesas e conhecimentos do budismo esotérico para criar este sistema de cura natural. Após sua morte em 1926, o Reiki foi preservado e transmitido por seus discípulos, especialmente Chujiro Hayashi, que sistematizou as posições das mãos e os tratamentos. Hawayo Takata trouxe o Reiki para o Ocidente na década de 1970, onde se expandiu mundialmente. No Brasil, chegou na década de 1980 e foi oficialmente incluído no Sistema Único de Saúde em 2017 como uma das práticas integrativas e complementares reconhecidas, sendo oferecido gratuitamente em diversos hospitais, UBS e centros de saúde.',
    application: 'O Reiki é aplicado através da imposição suave das mãos sobre pontos específicos do corpo (cabeça, tronco, membros) seguindo posições tradicionais sistematizadas, ou pode ser enviado à distância através de técnicas específicas de canalização energética. Durante a sessão, que dura entre 45 a 90 minutos, o receptor permanece vestido e deitado confortavelmente em uma maca, em ambiente tranquilo e harmonioso. O praticante coloca as mãos levemente sobre ou próximo ao corpo do receptor, permitindo que a energia flua naturalmente para onde é mais necessária. A energia Reiki é inteligente e vai automaticamente para os pontos que precisam de cura e reequilíbrio. Pode ser realizado em hospitais, clínicas, domicílio ou centros terapêuticos, sempre respeitando a privacidade e o conforto do receptor. Também pode ser aplicado em plantas, animais e situações diversas.',
    indications: 'Transtornos de ansiedade, síndrome do pânico e estresse pós-traumático, depressão leve a moderada e distúrbios do humor, dores crônicas (fibromialgia, artrite, dores nas costas), insônia e outros distúrbios do sono, fadiga crônica e síndrome de burnout, desequilíbrios emocionais, traumas e lutos, recuperação pós-cirúrgica e pós-tratamentos médicos invasivos, fortalecimento do sistema imunológico e prevenção de doenças, busca por equilíbrio energético e desenvolvimento espiritual, preparação para cirurgias e procedimentos médicos, alívio de efeitos colaterais de quimioterapia e radioterapia, hipertensão arterial e problemas cardiovasculares, distúrbios digestivos e problemas gastrointestinais, dores de cabeça e enxaquecas, problemas respiratórios e alergias, e como complemento em tratamentos de dependência química e vícios.',
    benefits: 'Redução significativa do estresse, ansiedade e tensão emocional através do relaxamento profundo do sistema nervoso, alívio eficaz de dores físicas e desconfortos corporais, melhora substancial da qualidade e profundidade do sono, equilíbrio emocional e estabilização do humor, fortalecimento e revitalização da energia vital e disposição física, aceleração natural dos processos de cura e regeneração celular, promoção de relaxamento profundo e renovação energética, aumento considerável da sensação de bem-estar, paz interior e serenidade, melhora da concentração, clareza mental e capacidade de foco, fortalecimento do sistema imunológico e aumento da resistência a doenças, harmonização dos chakras e centros energéticos, desenvolvimento da intuição e conexão espiritual, redução da pressão arterial e melhora da circulação sanguínea, e promoção de um estado geral de harmonia entre corpo, mente e espírito.',
    contraindications: 'O Reiki não possui contraindicações absolutas, sendo uma prática completamente segura que pode ser utilizada por pessoas de todas as idades, desde recém-nascidos até idosos, incluindo gestantes em qualquer período da gravidez. É seguro para pacientes com qualquer condição de saúde, pois a energia Reiki é inteligente e nunca causa danos, fluindo apenas na quantidade e intensidade adequadas para cada pessoa. Pode ser aplicado em conjunto com qualquer tratamento médico convencional sem interferências ou efeitos colaterais. A única precaução necessária é manter expectativas realistas sobre os resultados, compreendendo que o Reiki é uma terapia complementar que atua gradualmente e de forma sutil. Pessoas com marca-passo ou dispositivos eletrônicos implantados podem receber Reiki normalmente, pois não há interferência eletromagnética. É importante que o receptor esteja aberto e receptivo ao tratamento para obter melhores resultados.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '6',
    name: 'Auriculoterapia',
    definition: 'A Auriculoterapia é uma técnica terapêutica refinada e científica que utiliza pontos específicos da orelha (pavilhão auricular) para diagnóstico preciso e tratamento eficaz de diversas condições de saúde física, mental e emocional. Baseada no princípio fundamental de que a orelha é um microssistema completo que reflete e representa todo o corpo humano em miniatura, esta prática milenar utiliza sementes naturais, esferas metálicas, cristais, magnetos ou microagulhas aplicadas em pontos auriculares específicos mapeados anatomicamente. A estimulação desses pontos reflexos envia impulsos neurológicos diretos ao sistema nervoso central através do nervo vago e outros nervos cranianos, promovendo o reequilíbrio energético, a autorregulação do organismo e a liberação de neurotransmissores como endorfinas e serotonina. É uma técnica completamente segura, minimamente invasiva, de fácil aplicação e alta eficácia, que pode ser utilizada como tratamento principal ou complementar a outras terapias, oferecendo resultados rápidos e duradouros.',
    origin: 'Desenvolvida cientificamente na França pelo médico neurologista Dr. Paul Nogier na década de 1950, após observar cicatrizes de cauterização na orelha de pacientes que haviam sido tratados para dor ciática por uma curandeira local. Nogier mapeou sistematicamente os pontos auriculares e criou o "mapa do feto invertido" na orelha, estabelecendo as bases da auriculoterapia moderna. Embora tenha raízes na Medicina Tradicional Chinesa, que já utilizava pontos da orelha há milhares de anos, a sistematização ocidental de Nogier revolucionou a prática. A técnica foi posteriormente aperfeiçoada por pesquisadores chineses e franceses, sendo reconhecida pela Organização Mundial da Saúde em 1990. No Brasil, foi incluída no Sistema Único de Saúde como parte da Medicina Tradicional Chinesa e das práticas integrativas, sendo amplamente utilizada em hospitais, UBS e clínicas especializadas.',
    application: 'A auriculoterapia é aplicada através da colocação precisa de sementes de mostarda ou colza, esferas metálicas douradas ou prateadas, cristais, magnetos ou microagulhas descartáveis em pontos específicos da orelha, previamente identificados através de palpação, inspeção visual ou detectores eletrônicos de pontos ativos. Os materiais permanecem fixados com micropore hipoalergênico por 3 a 7 dias, durante os quais o paciente deve estimular os pontos através de leve pressão circular 3 a 5 vezes ao dia conforme orientação profissional. O tratamento é indolor e pode ser aplicado em uma ou ambas as orelhas, dependendo da condição tratada. As sessões são realizadas semanalmente ou quinzenalmente, com duração de 20 a 30 minutos, em ambiente limpo e esterilizado. É fundamental que seja realizada por profissional capacitado em auriculoterapia.',
    indications: 'Dores crônicas (fibromialgia, artrite, artrose, dores nas costas, cervicalgia), transtornos de ansiedade e síndrome do pânico, depressão leve a moderada e distúrbios do humor, insônia e outros distúrbios do sono, tabagismo e dependência de nicotina, dependência química (álcool, drogas), obesidade e transtornos alimentares (compulsão alimentar, bulimia), enxaqueca e dores de cabeça tensionais, hipertensão arterial e problemas cardiovasculares, problemas digestivos (gastrite, síndrome do intestino irritável, constipação), distúrbios emocionais e estresse pós-traumático, TPM e sintomas da menopausa, zumbido no ouvido (tinnitus), alergias respiratórias e asma, problemas de concentração e memória, e como coadjuvante em tratamentos de reabilitação e recuperação pós-cirúrgica.',
    benefits: 'Alívio rápido e eficaz da dor através da liberação de endorfinas naturais, redução significativa do estresse, ansiedade e tensão emocional, melhora substancial da qualidade e profundidade do sono, auxílio poderoso no controle e cessação de vícios e dependências, regulação natural do apetite e metabolismo para controle de peso, melhora considerável do humor e estabilização emocional, fortalecimento do sistema imunológico e aumento da resistência a doenças, promoção do equilíbrio energético e harmonização dos sistemas corporais, redução da pressão arterial e melhora da circulação sanguínea, alívio de sintomas de abstinência em tratamentos de dependência, melhora da concentração e clareza mental, regulação hormonal natural, redução de inflamações e processos alérgicos, e promoção de um estado geral de relaxamento e bem-estar duradouro.',
    contraindications: 'Infecções ativas ou feridas abertas na orelha (requer tratamento prévio), gravidez (alguns pontos específicos podem estimular contrações uterinas), marca-passo cardíaco ou dispositivos eletrônicos implantados (para eletroacupuntura auricular), alergia conhecida aos materiais utilizados (sementes, metais, adesivos), distúrbios graves de coagulação sanguínea ou uso de anticoagulantes potentes, lesões cutâneas severas no pavilhão auricular, transtornos psiquiátricos graves em fase aguda, epilepsia não controlada (cuidado com estimulação excessiva), e pacientes com tendência a queloides ou cicatrização anormal. Crianças muito pequenas podem ter dificuldade em manter os materiais fixados.',
    imageUrl: 'https://images.pexels.com/photos/5473298/pexels-photo-5473298.jpeg',
  },
  {
    id: '7',
    name: 'Ayurveda',
    definition: 'O Ayurveda é um sistema médico tradicional originário da Índia com mais de 5.000 anos de história. Considerado uma das medicinas mais antigas do mundo, o Ayurveda significa "ciência da vida" em sânscrito e baseia-se no princípio de que a saúde resulta do equilíbrio entre corpo, mente e espírito. Este sistema utiliza uma abordagem holística que inclui diagnóstico através dos doshas (tipos constitucionais), tratamentos personalizados com plantas medicinais, dieta específica, práticas de purificação, massagens terapêuticas, yoga e meditação. O objetivo é prevenir doenças e promover longevidade através do equilíbrio dos elementos naturais do corpo.',
    origin: 'Originário da Índia há mais de 5.000 anos, documentado nos textos sagrados Vedas. Foi incluído no SUS em 2006 como uma das primeiras práticas integrativas reconhecidas.',
    application: 'Consulta ayurvédica para determinação do dosha, prescrição de plantas medicinais, orientação dietética personalizada, massagens com óleos específicos, práticas de purificação (panchakarma), yoga e meditação.',
    indications: 'Distúrbios digestivos, estresse, ansiedade, insônia, dores articulares, problemas de pele, desequilíbrios hormonais, fadiga crônica, hipertensão e prevenção de doenças.',
    benefits: 'Melhora da digestão e metabolismo, redução do estresse, fortalecimento da imunidade, equilíbrio hormonal, melhora da qualidade do sono, aumento da energia vital, promoção da longevidade e prevenção de doenças.',
    contraindications: 'Algumas preparações podem ser contraindicadas na gravidez, lactação, crianças pequenas, doenças graves agudas, alergias específicas a plantas medicinais e interações com medicamentos convencionais.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '8',
    name: 'Biodança',
    definition: 'A Biodança é um sistema de integração humana, renovação orgânica, reeducação afetiva e reaprendizagem das funções originárias da vida. Criada pelo psicólogo e antropólogo chileno Rolando Toro, esta prática utiliza a música, o movimento e situações de encontro em grupo para estimular vivências integradoras. A Biodança trabalha com cinco linhas de vivência: vitalidade, sexualidade, criatividade, afetividade e transcendência, promovendo o desenvolvimento do potencial humano através da expressão corporal espontânea. É uma metodologia que busca restaurar a conexão com a vida, desenvolvendo a identidade e integrando as dimensões física, emocional, mental e espiritual do ser humano.',
    origin: 'Criada na década de 1960 pelo psicólogo chileno Rolando Toro Araneda. Foi incluída no SUS em 2017 como prática integrativa e complementar.',
    application: 'Sessões em grupo com duração de 2 a 3 horas, conduzidas por facilitador habilitado. Utiliza música específica, exercícios de movimento, danças e vivências de encontro para estimular as cinco linhas de vivência.',
    indications: 'Depressão, ansiedade, estresse, baixa autoestima, dificuldades de relacionamento, timidez excessiva, rigidez corporal, falta de vitalidade, problemas de expressão emocional e isolamento social.',
    benefits: 'Aumento da vitalidade e energia, melhora da autoestima, desenvolvimento da criatividade, fortalecimento de vínculos afetivos, redução do estresse, maior flexibilidade corporal e emocional, e integração psicossomática.',
    contraindications: 'Surtos psicóticos agudos, transtornos dissociativos graves, epilepsia não controlada, problemas cardíacos severos que impeçam atividade física moderada, e resistência extrema ao contato corporal.',
    imageUrl: 'https://images.pexels.com/photos/1701194/pexels-photo-1701194.jpeg',
  },
  {
    id: '9',
    name: 'Bioenergética',
    definition: 'A Bioenergética é uma abordagem terapêutica que integra trabalho corporal e psicoterapia, desenvolvida por Alexander Lowen baseada nos trabalhos de Wilhelm Reich. Esta prática entende que os conflitos emocionais se manifestam como tensões e bloqueios no corpo, criando "couraças musculares" que limitam a expressão natural da energia vital. Através de exercícios específicos, respiração, movimento, expressão vocal e toque terapêutico, a bioenergética busca liberar essas tensões, restaurar o fluxo energético natural e promover a integração entre corpo e mente. É uma terapia que trabalha simultaneamente com aspectos físicos e emocionais, promovendo maior vitalidade, autoconhecimento e bem-estar.',
    origin: 'Desenvolvida por Alexander Lowen na década de 1950, baseada nos trabalhos de Wilhelm Reich sobre energia corporal. Foi incluída no SUS em 2018.',
    application: 'Sessões individuais ou em grupo com exercícios de respiração, movimentos expressivos, posturas específicas, vocalização, trabalho com tensões musculares e técnicas de grounding (enraizamento).',
    indications: 'Ansiedade, depressão, estresse crônico, tensões musculares, bloqueios emocionais, baixa autoestima, dificuldades de relacionamento, problemas sexuais, traumas e rigidez corporal.',
    benefits: 'Liberação de tensões musculares, aumento da vitalidade, melhora da respiração, maior consciência corporal, expressão emocional saudável, redução do estresse, fortalecimento da autoestima e integração psicossomática.',
    contraindications: 'Transtornos psicóticos agudos, problemas cardíacos graves, hipertensão severa não controlada, gravidez (alguns exercícios), lesões musculoesqueléticas agudas e epilepsia não controlada.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  },
  {
    id: '10',
    name: 'Constelação Familiar',
    definition: 'A Constelação Familiar é uma abordagem terapêutica sistêmica desenvolvida por Bert Hellinger que busca identificar e harmonizar dinâmicas ocultas dentro dos sistemas familiares que podem estar causando sofrimento, conflitos ou dificuldades na vida das pessoas. Esta prática baseia-se na ideia de que existem "ordens do amor" e lealdades inconscientes que conectam os membros de uma família através de gerações. Através de representações espaciais, onde participantes representam membros da família, é possível visualizar e transformar padrões disfuncionais, traumas não resolvidos e exclusões familiares. O objetivo é restaurar o fluxo do amor e promover a paz no sistema familiar.',
    origin: 'Desenvolvida pelo psicoterapeuta alemão Bert Hellinger a partir da década de 1980, integrando elementos da terapia familiar sistêmica, fenomenologia e filosofias orientais. Foi incluída no SUS em 2018.',
    application: 'Sessões em grupo onde o cliente escolhe representantes para membros de sua família. O facilitador conduz o processo observando movimentos e sensações dos representantes para identificar dinâmicas familiares e promover movimentos de solução.',
    indications: 'Conflitos familiares, dificuldades de relacionamento, padrões repetitivos destrutivos, luto não elaborado, problemas com ancestralidade, bloqueios profissionais, depressão, ansiedade e traumas familiares.',
    benefits: 'Compreensão de dinâmicas familiares inconscientes, resolução de conflitos ancestrais, liberação de padrões limitantes, melhora nos relacionamentos, maior clareza sobre o lugar na família, paz interior e reconciliação familiar.',
    contraindications: 'Transtornos psicóticos agudos, personalidade borderline em crise, dependência química ativa, resistência extrema ao trabalho sistêmico e expectativas irreais sobre resultados imediatos.',
    imageUrl: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg',
  },
  {
    id: '11',
    name: 'Cromoterapia',
    definition: 'A Cromoterapia é uma terapia que utiliza as cores e suas frequências vibracionais para promover o equilíbrio energético e o bem-estar físico, mental e emocional. Baseada no princípio de que cada cor possui uma frequência específica que pode influenciar os centros energéticos (chakras) e os sistemas do corpo humano, esta prática utiliza luz colorida, visualizações, ambientes coloridos e objetos coloridos para fins terapêuticos. Cada cor possui propriedades específicas: o vermelho estimula e energiza, o azul acalma e relaxa, o verde equilibra e harmoniza, o amarelo estimula a mente, entre outras. É uma terapia suave e não invasiva que pode ser facilmente integrada a outras práticas terapêuticas.',
    origin: 'Utilizada por civilizações antigas como egípcios, gregos e chineses. Foi sistematizada no século XIX e incluída no SUS em 2018 como prática integrativa.',
    application: 'Exposição à luz colorida através de lâmpadas especiais, visualização de cores, banhos de luz colorida, uso de roupas e objetos coloridos, ambientação com cores específicas e meditação com cores.',
    indications: 'Estresse, ansiedade, depressão, insônia, fadiga, dores de cabeça, hipertensão, problemas digestivos, desequilíbrios emocionais e baixa autoestima.',
    benefits: 'Equilíbrio energético, redução do estresse, melhora do humor, harmonização emocional, estímulo da criatividade, fortalecimento da vitalidade, melhora da concentração e promoção do relaxamento.',
    contraindications: 'Epilepsia fotossensível, enxaqueca desencadeada por luz, alguns tipos de câncer de pele (exposição direta), transtornos bipolares em fase maníaca e hipersensibilidade à luz.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '12',
    name: 'Dança Circular',
    definition: 'A Dança Circular é uma prática integrativa que utiliza danças tradicionais de diversos povos e culturas, realizadas em círculo, para promover integração social, bem-estar emocional e desenvolvimento pessoal. Esta modalidade resgata danças sagradas e folclóricas de diferentes tradições, adaptando-as para fins terapêuticos e educativos. O círculo simboliza unidade, igualdade e inclusão, criando um espaço seguro onde todos podem participar independentemente de idade, condição física ou experiência em dança. As coreografias simples e repetitivas facilitam a concentração, a meditação em movimento e a conexão com o grupo, promovendo senso de pertencimento e comunidade.',
    origin: 'Baseada em danças tradicionais de diversos povos. Foi sistematizada como prática terapêutica no século XX e incluída no SUS em 2017.',
    application: 'Sessões em grupo conduzidas por facilitador qualificado, utilizando músicas tradicionais de diferentes culturas, movimentos simples e coreografias em círculo que promovem integração e bem-estar.',
    indications: 'Isolamento social, depressão, ansiedade, baixa autoestima, estresse, rigidez corporal, dificuldades de socialização, luto, traumas e necessidade de integração comunitária.',
    benefits: 'Fortalecimento de vínculos sociais, melhora da autoestima, redução do estresse, aumento da flexibilidade, desenvolvimento da coordenação motora, expressão emocional saudável e senso de pertencimento.',
    contraindications: 'Problemas cardíacos graves que impeçam atividade física leve, lesões musculoesqueléticas agudas, vertigem severa, fobia social extrema e resistência total ao movimento corporal.',
    imageUrl: 'https://images.pexels.com/photos/1701194/pexels-photo-1701194.jpeg',
  },
  {
    id: '13',
    name: 'Fitoterapia',
    definition: 'A Fitoterapia é a ciência que estuda o uso de plantas medicinais para a prevenção, tratamento e cura de doenças. Esta prática milenar utiliza plantas in natura ou preparações derivadas (extratos, tinturas, cápsulas, chás) que contêm princípios ativos com propriedades terapêuticas comprovadas cientificamente. A fitoterapia combina conhecimento tradicional com pesquisa científica moderna, oferecendo alternativas naturais para diversos problemas de saúde. No Brasil, a fitoterapia é regulamentada pela ANVISA e integra a Política Nacional de Plantas Medicinais e Fitoterápicos, sendo uma das práticas mais utilizadas no SUS. É importante que seja prescrita por profissionais qualificados para garantir segurança e eficácia.',
    origin: 'Prática milenar presente em todas as culturas humanas. Foi incluída no SUS em 2006 como uma das primeiras práticas integrativas reconhecidas.',
    application: 'Prescrição de plantas medicinais in natura, chás, extratos secos, tinturas, cápsulas e outros preparados fitoterápicos, sempre com orientação profissional qualificada.',
    indications: 'Ansiedade, insônia, problemas digestivos, infecções respiratórias, dores articulares, hipertensão leve, problemas de pele, TPM, menopausa e diversas condições crônicas.',
    benefits: 'Tratamento natural com menos efeitos colaterais, ação suave e progressiva, fortalecimento da imunidade, melhora da qualidade de vida, baixo custo e sustentabilidade ambiental.',
    contraindications: 'Pode interagir com medicamentos convencionais, gravidez e lactação (algumas plantas), alergias específicas, doenças graves que requerem tratamento convencional urgente e automedicação sem orientação.',
    imageUrl: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  },
  {
    id: '14',
    name: 'Meditação',
    definition: 'A Meditação é uma prática milenar de treinamento mental que visa desenvolver a atenção plena, concentração, consciência do momento presente e equilíbrio emocional. Esta técnica envolve o direcionamento da atenção para um objeto específico (respiração, mantra, sensações corporais) ou para a observação dos pensamentos e emoções sem julgamento. A meditação promove um estado de relaxamento profundo e alerta consciente, permitindo que a mente se acalme e se torne mais clara. Existem diversas técnicas meditativas, desde as tradicionais orientais até abordagens modernas baseadas em evidências científicas, todas visando o bem-estar integral do praticante.',
    origin: 'Presente em diversas tradições espirituais há milhares de anos, especialmente no budismo, hinduísmo e taoísmo. Foi incluída no SUS em 2017 como prática integrativa.',
    application: 'Prática individual ou em grupo, utilizando técnicas como meditação da respiração, mindfulness, meditação transcendental, body scan, caminhada meditativa e visualizações guiadas.',
    indications: 'Estresse, ansiedade, depressão, insônia, hipertensão, dor crônica, transtorno de déficit de atenção, síndrome do pânico, burnout e busca por autoconhecimento.',
    benefits: 'Redução do estresse e ansiedade, melhora da concentração e memória, equilíbrio emocional, redução da pressão arterial, fortalecimento do sistema imunológico, melhora da qualidade do sono e aumento da autoconsciência.',
    contraindications: 'Geralmente segura, mas pessoas com transtornos psicóticos agudos, depressão severa ou transtorno bipolar em crise devem praticar sob orientação profissional.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  },
  {
    id: '5',
    name: 'Reiki',
    definition: 'O Reiki é uma terapia integrativa de origem japonesa que se baseia na canalização da "energia universal" (Rei) através da imposição das mãos com o objetivo de restabelecer o equilíbrio dos centros de energia do corpo, conhecidos como chakras, promovendo bem-estar físico e mental.',
    origin: 'Foi sistematizado por Mikao Usui no Japão em 1922. Chegou ao Ocidente (Havaí) por volta de 1938-1940, através de Hawayo Takata, e foi introduzido no Brasil em 1983 por Claudete França e Johnny De\'Carli.',
    application: 'O terapeuta reikiano, após ser sintonizado com a energia Reiki, posiciona as mãos sobre ou próximo aos principais chakras do paciente ou em áreas específicas que necessitam de tratamento, canalizando a energia vital universal. Não está ligado a nenhuma religião.',
    indications: 'É indicado para uma ampla gama de desequilíbrios, como estresse, ansiedade, depressão leve, dores crônicas, insônia, fadiga e náuseas. A OMS reconheceu o Reiki em 2007 como uma terapia auxiliar no tratamento da dor.',
    benefits: 'Promove relaxamento profundo, redução da ansiedade e do estresse, alívio de dores, melhora da qualidade do sono e da qualidade de vida geral, e fortalecimento do sistema imunológico. Estudos qualitativos e alguns ensaios clínicos randomizados relatam efeitos positivos.',
    contraindications: 'Não possui contraindicações absolutas conhecidas nem efeitos colaterais. Pode ser aplicado em conjunto com outras terapias e tratamentos convencionais, mas não os substitui.',
    imageUrl: 'https://sdmntprcentralus.oaiusercontent.com/files/00000000-1028-61f5-aa1b-f34628216436/raw?se=2025-06-01T21%3A30%3A05Z&sp=r&sv=2024-08-04&sr=b&scid=acda1189-1064-5ff9-8e71-1658a47537a8&skoid=add8ee7d-5fc7-451e-b06e-a82b2276cf62&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-06-01T20%3A28%3A52Z&ske=2025-06-02T20%3A28%3A52Z&sks=b&skv=2024-08-04&sig=Y4LFAGdG8h9ysr3ozj86MDLj8AAGGa%2BizlvA/S3UNRw%3D',
  },
  {
    id: '15',
    name: 'Geoterapia',
    definition: 'A Geoterapia é uma prática terapêutica que utiliza elementos da terra como argila, lama, areia e pedras para fins curativos e de bem-estar. Esta terapia natural aproveita as propriedades minerais e energéticas dos elementos terrestres para promover desintoxicação, cicatrização, relaxamento e equilíbrio energético. A argila, principal elemento utilizado, possui propriedades absorventes, anti-inflamatórias e remineralizantes que beneficiam a pele e o organismo. A geoterapia pode incluir banhos de argila, cataplasmas, máscaras faciais e corporais, além de técnicas de contato direto com a terra. É uma prática que reconecta o ser humano com os elementos naturais, promovendo cura holística.',
    origin: 'Prática milenar utilizada por diversas civilizações antigas. Foi sistematizada e incluída no SUS em 2018 como prática integrativa.',
    application: 'Aplicação de argila medicinal, lamas terapêuticas, banhos de terra, cataplasmas e máscaras, sempre com orientação profissional adequada.',
    indications: 'Problemas de pele, inflamações, dores articulares, estresse, ansiedade, desintoxicação, cicatrização de feridas e desequilíbrios energéticos.',
    benefits: 'Desintoxicação do organismo, melhora da circulação, ação anti-inflamatória, cicatrização, relaxamento, equilíbrio energético e reconexão com a natureza.',
    contraindications: 'Feridas abertas infectadas, alergias a componentes da argila, problemas renais graves, hipertensão severa e gravidez (algumas aplicações).',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '16',
    name: 'Hipnoterapia',
    definition: 'A Hipnoterapia é uma abordagem terapêutica que utiliza o estado de hipnose para acessar o subconsciente e promover mudanças comportamentais, emocionais e físicas positivas. Durante o estado hipnótico, a pessoa mantém-se consciente mas em um estado de relaxamento profundo e concentração focada, permitindo maior receptividade a sugestões terapêuticas. Esta prática é conduzida por profissionais qualificados e pode ser utilizada para tratar diversos problemas psicológicos, vícios, fobias, dores crônicas e distúrbios psicossomáticos. A hipnoterapia é baseada em evidências científicas e é reconhecida como uma ferramenta terapêutica eficaz quando aplicada adequadamente.',
    origin: 'Desenvolvida a partir dos trabalhos de Franz Anton Mesmer no século XVIII e sistematizada por Milton Erickson no século XX. Foi incluída no SUS em 2018.',
    application: 'Sessões individuais conduzidas por hipnoterapeuta qualificado, utilizando técnicas de indução hipnótica, sugestões terapêuticas e programação neurolinguística.',
    indications: 'Ansiedade, fobias, depressão, vícios (tabagismo, alcoolismo), dores crônicas, insônia, transtornos alimentares, traumas e distúrbios psicossomáticos.',
    benefits: 'Redução da ansiedade, superação de fobias e vícios, alívio de dores crônicas, melhora do sono, mudanças comportamentais positivas e autoconhecimento.',
    contraindications: 'Transtornos psicóticos, esquizofrenia, transtorno bipolar em crise, epilepsia não controlada, retardo mental severo e resistência extrema à hipnose.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  },
  {
    id: '17',
    name: 'Imposição de Mãos',
    definition: 'A Imposição de Mãos é uma prática terapêutica ancestral que utiliza a energia das mãos do terapeuta para promover cura, alívio de sintomas e bem-estar. Esta técnica baseia-se no princípio de que existe uma energia vital universal que pode ser canalizada através das mãos para harmonizar os centros energéticos do corpo e estimular os processos naturais de cura. O terapeuta posiciona as mãos sobre ou próximo ao corpo do paciente, sem necessariamente tocá-lo, direcionando energia curativa para áreas específicas. É uma prática suave, não invasiva e complementar que pode ser utilizada junto com outros tratamentos médicos convencionais.',
    origin: 'Prática ancestral presente em diversas tradições espirituais e culturais ao longo da história. Foi incluída no SUS em 2017.',
    application: 'Posicionamento das mãos sobre ou próximo ao corpo do paciente, canalizando energia curativa para promover equilíbrio e bem-estar, sem manipulação física.',
    indications: 'Dores crônicas, estresse, ansiedade, depressão, fadiga, desequilíbrios energéticos, recuperação pós-cirúrgica e fortalecimento do sistema imunológico.',
    benefits: 'Alívio de dores, redução do estresse, relaxamento profundo, equilíbrio energético, fortalecimento da energia vital e aceleração de processos de cura.',
    contraindications: 'Não há contraindicações absolutas. É uma prática segura que pode ser utilizada por pessoas de todas as idades.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '18',
    name: 'Medicina Antroposófica',
    definition: 'A Medicina Antroposófica é um sistema médico integrativo desenvolvido por Rudolf Steiner que amplia a medicina convencional com uma compreensão do ser humano que inclui dimensões físicas, etéricas, anímicas e espirituais. Esta abordagem utiliza medicamentos antroposóficos, terapias artísticas, euritmia curativa, massagem rítmica e outras modalidades terapêuticas. O diagnóstico e tratamento consideram não apenas os sintomas físicos, mas também a constituição individual, biografia, temperamento e desenvolvimento espiritual da pessoa. É uma medicina que busca estimular as forças de autocura do organismo através de uma abordagem holística e individualizada.',
    origin: 'Desenvolvida por Rudolf Steiner no início do século XX em colaboração com médicos. Foi incluída no SUS em 2006.',
    application: 'Consultas médicas especializadas, prescrição de medicamentos antroposóficos, terapias artísticas, euritmia curativa, massagem rítmica e orientações sobre estilo de vida.',
    indications: 'Doenças crônicas, transtornos do desenvolvimento, problemas emocionais, doenças autoimunes, câncer (como terapia complementar) e condições que requerem abordagem integrativa.',
    benefits: 'Tratamento individualizado, fortalecimento da autocura, melhora da qualidade de vida, desenvolvimento da consciência e promoção do equilíbrio integral.',
    contraindications: 'Não substitui tratamentos convencionais em emergências. Deve ser praticada por profissionais qualificados em medicina antroposófica.',
    imageUrl: 'https://images.pexels.com/photos/6823568/pexels-photo-6823568.jpeg',
  },
  {
    id: '19',
    name: 'Medicina Tradicional Chinesa',
    definition: 'A Medicina Tradicional Chinesa (MTC) é um sistema médico milenar que compreende diversas práticas terapêuticas baseadas na filosofia chinesa do equilíbrio entre Yin e Yang e na teoria dos cinco elementos. A MTC inclui acupuntura, fitoterapia chinesa, massagem Tui Ná, ventosaterapia, moxabustão e práticas corporais como Qi Gong e Tai Chi Chuan. Este sistema médico considera o ser humano como um todo integrado, onde a saúde resulta do fluxo harmonioso da energia vital (Qi) através dos meridianos do corpo. O diagnóstico é realizado através da observação, palpação, ausculta e anamnese detalhada.',
    origin: 'Sistema médico com mais de 3.000 anos de história, originário da China. Foi incluído no SUS em 2006.',
    application: 'Diagnóstico através dos métodos tradicionais chineses e aplicação de técnicas como acupuntura, fitoterapia, massagem, ventosaterapia e práticas corporais.',
    indications: 'Dores crônicas, problemas digestivos, distúrbios emocionais, problemas respiratórios, hipertensão, artrite, insônia e desequilíbrios energéticos.',
    benefits: 'Tratamento holístico, equilíbrio energético, fortalecimento da vitalidade, prevenção de doenças, melhora da qualidade de vida e harmonização corpo-mente.',
    contraindications: 'Algumas técnicas podem ter contraindicações específicas. Deve ser praticada por profissionais qualificados em MTC.',
    imageUrl: 'https://images.pexels.com/photos/5473298/pexels-photo-5473298.jpeg',
  },
  {
    id: '20',
    name: 'Naturopatia',
    definition: 'A Naturopatia é um sistema de medicina natural que utiliza métodos não invasivos para estimular a capacidade inata de autocura do organismo. Esta abordagem holística combina conhecimentos tradicionais com ciências modernas, utilizando recursos naturais como plantas medicinais, alimentação, hidroterapia, exercícios, técnicas de relaxamento e mudanças no estilo de vida. O naturopata busca identificar e tratar as causas subjacentes das doenças, não apenas os sintomas, promovendo a saúde através da harmonização entre o indivíduo e seu ambiente. A naturopatia enfatiza a prevenção e a educação do paciente para que ele se torne responsável por sua própria saúde.',
    origin: 'Baseada em tradições de cura natural de diversas culturas, sistematizada no século XIX. Foi incluída no SUS em 2018.',
    application: 'Consultas naturopáticas com prescrição de plantas medicinais, orientação nutricional, hidroterapia, técnicas de desintoxicação e mudanças no estilo de vida.',
    indications: 'Doenças crônicas, problemas digestivos, alergias, fadiga crônica, estresse, desequilíbrios hormonais, problemas de pele e prevenção de doenças.',
    benefits: 'Tratamento natural sem efeitos colaterais, fortalecimento da imunidade, melhora da vitalidade, prevenção de doenças, educação em saúde e autocuidado.',
    contraindications: 'Não substitui tratamentos médicos convencionais em doenças graves. Algumas plantas podem interagir com medicamentos.',
    imageUrl: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  },
  {
    id: '21',
    name: 'Osteopatia',
    definition: 'A Osteopatia é uma abordagem terapêutica manual que se baseia no princípio de que o corpo possui mecanismos de autorregulação e autocura. Desenvolvida por Andrew Taylor Still, esta prática utiliza técnicas manuais específicas para diagnosticar, tratar e prevenir disfunções do sistema musculoesquelético e suas repercussões na saúde geral. O osteopata trabalha com manipulações articulares, técnicas de tecidos moles, mobilizações e outras abordagens manuais para restaurar a mobilidade, melhorar a circulação e promover o equilíbrio estrutural do corpo. A osteopatia considera a inter-relação entre estrutura e função, tratando o corpo como uma unidade integrada.',
    origin: 'Desenvolvida por Andrew Taylor Still nos Estados Unidos no final do século XIX. Foi incluída no SUS em 2018.',
    application: 'Avaliação osteopática e aplicação de técnicas manuais específicas para correção de disfunções estruturais e funcionais do corpo.',
    indications: 'Dores nas costas, problemas posturais, dores de cabeça, lesões esportivas, problemas articulares, tensões musculares e disfunções viscerais.',
    benefits: 'Alívio de dores, melhora da mobilidade, correção postural, redução de tensões, melhora da circulação e restauração do equilíbrio corporal.',
    contraindications: 'Fraturas agudas, infecções ósseas, tumores malignos, osteoporose severa, artrite reumatoide em fase aguda e instabilidade articular grave.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  },
  {
    id: '22',
    name: 'Ozonioterapia',
    definition: 'A Ozonioterapia é uma prática terapêutica que utiliza o ozônio medicinal (mistura de oxigênio e ozônio) para fins curativos e preventivos. O ozônio possui propriedades antimicrobianas, anti-inflamatórias, imunomoduladoras e oxigenantes que podem beneficiar diversos sistemas do organismo. Esta terapia pode ser aplicada por diferentes vias: tópica, retal, intramuscular, intravenosa ou através de auto-hemoterapia. A ozonioterapia estimula o sistema imunológico, melhora a oxigenação dos tecidos, possui ação antioxidante e pode auxiliar no tratamento de diversas condições de saúde. É importante que seja aplicada por profissionais qualificados e com equipamentos adequados.',
    origin: 'O ozônio foi descoberto em 1840 e suas propriedades terapêuticas foram estudadas desde então. Foi incluída no SUS em 2018.',
    application: 'Aplicação de ozônio medicinal por diferentes vias (tópica, retal, intramuscular, intravenosa) conforme indicação e sempre com supervisão profissional.',
    indications: 'Infecções, feridas de difícil cicatrização, problemas circulatórios, fadiga crônica, doenças autoimunes, problemas de pele e fortalecimento imunológico.',
    benefits: 'Ação antimicrobiana, melhora da oxigenação, fortalecimento imunológico, ação anti-inflamatória, aceleração da cicatrização e desintoxicação.',
    contraindications: 'Deficiência de G6PD, hipertireoidismo, gravidez, problemas cardíacos graves, anemia severa e alergia ao ozônio.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '23',
    name: 'Quiropraxia',
    definition: 'A Quiropraxia é uma profissão da área da saúde que se dedica ao diagnóstico, tratamento e prevenção de distúrbios do sistema neuromusculoesquelético e seus efeitos na saúde geral. Os quiropráticos utilizam principalmente técnicas manuais, especialmente ajustes articulares (manipulações), para corrigir disfunções da coluna vertebral e outras articulações do corpo. Esta abordagem baseia-se no princípio de que o sistema nervoso controla todas as funções do corpo e que disfunções articulares podem interferir na comunicação neural, causando dor e outros problemas de saúde. A quiropraxia enfatiza a capacidade natural do corpo de se curar sem o uso de medicamentos ou cirurgias.',
    origin: 'Fundada por Daniel David Palmer em 1895 nos Estados Unidos. Foi incluída no SUS em 2018.',
    application: 'Avaliação quiroprática e aplicação de ajustes articulares manuais específicos para correção de subluxações e disfunções articulares.',
    indications: 'Dores nas costas, dores no pescoço, dores de cabeça, problemas posturais, lesões esportivas, ciática e disfunções articulares.',
    benefits: 'Alívio de dores, melhora da mobilidade articular, correção postural, redução de tensões musculares e melhora da função neurológica.',
    contraindications: 'Fraturas, tumores ósseos, infecções articulares, osteoporose severa, instabilidade articular e algumas condições neurológicas.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  },
  {
    id: '24',
    name: 'Reflexoterapia',
    definition: 'A Reflexoterapia é uma técnica terapêutica que utiliza a estimulação de pontos reflexos específicos nos pés, mãos, orelhas e outras partes do corpo para promover o equilíbrio e a cura de órgãos e sistemas correspondentes. Baseada no princípio de que existem zonas reflexas que se conectam com diferentes partes do corpo através do sistema nervoso, esta prática utiliza pressão, massagem e outras técnicas de estimulação para ativar os processos naturais de cura. A reflexoterapia mais conhecida é a podal (nos pés), mas também inclui a reflexoterapia das mãos, auricular e facial. É uma terapia não invasiva que pode proporcionar relaxamento profundo e alívio de diversos sintomas.',
    origin: 'Baseada em conhecimentos ancestrais de diversas culturas, sistematizada no século XX. Foi incluída no SUS em 2018.',
    application: 'Aplicação de pressão e massagem em pontos reflexos específicos dos pés, mãos ou orelhas, correspondentes aos órgãos e sistemas do corpo.',
    indications: 'Estresse, ansiedade, dores de cabeça, problemas digestivos, insônia, dores musculares, problemas circulatórios e desequilíbrios energéticos.',
    benefits: 'Relaxamento profundo, alívio de dores, melhora da circulação, redução do estresse, equilíbrio energético e estímulo dos processos de autocura.',
    contraindications: 'Trombose, infecções nos pés, feridas abertas, gravidez (alguns pontos), problemas cardíacos graves e febre alta.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '25',
    name: 'Rolfing',
    definition: 'O Rolfing, também conhecido como Integração Estrutural, é um método de trabalho corporal desenvolvido por Ida Rolf que visa reorganizar a estrutura corporal através da manipulação do tecido conjuntivo (fáscia). Esta técnica utiliza pressão profunda e movimentos específicos para liberar tensões crônicas, melhorar o alinhamento postural e restaurar a flexibilidade natural do corpo. O Rolfing trabalha com a ideia de que traumas físicos e emocionais podem criar padrões de tensão que alteram a estrutura corporal, e através da reorganização fascial é possível restaurar o equilíbrio e a funcionalidade. O tratamento geralmente é realizado em uma série de 10 sessões, cada uma focando em diferentes áreas do corpo.',
    origin: 'Desenvolvido por Ida Pauline Rolf nas décadas de 1940-1950 nos Estados Unidos. Foi incluído no SUS em 2018.',
    application: 'Manipulação profunda do tecido conjuntivo através de pressão manual específica, visando reorganizar a estrutura corporal e melhorar o alinhamento.',
    indications: 'Problemas posturais, dores crônicas, tensões musculares, limitações de movimento, lesões esportivas e desequilíbrios estruturais.',
    benefits: 'Melhora da postura, alívio de dores crônicas, aumento da flexibilidade, maior consciência corporal, redução de tensões e melhora da performance física.',
    contraindications: 'Inflamações agudas, infecções, fraturas recentes, osteoporose severa, problemas cardíacos graves e câncer em áreas de tratamento.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  },
  {
    id: '26',
    name: 'Satvatavajaya',
    definition: 'Satvatavajaya é uma das três principais modalidades terapêuticas do Ayurveda, focada especificamente no tratamento de distúrbios mentais e emocionais através de abordagens psicoterapêuticas. O termo significa "psicoterapia" em sânscrito e envolve técnicas de aconselhamento, reeducação mental, modificação de comportamentos inadequados e fortalecimento da mente. Esta prática utiliza métodos como meditação, mantras, visualizações, mudanças no estilo de vida, práticas espirituais e orientação filosófica para promover o equilíbrio mental e emocional. Satvatavajaya trabalha com os três gunas (qualidades mentais) - sattva, rajas e tamas - buscando aumentar sattva (pureza, clareza) e reduzir rajas (agitação) e tamas (inércia).',
    origin: 'Parte integrante do sistema Ayurvédico há mais de 5.000 anos, documentado nos textos clássicos como Charaka Samhita. Foi incluído no SUS em 2018.',
    application: 'Consultas especializadas com orientação psicoterapêutica ayurvédica, práticas meditativas, uso de mantras, mudanças no estilo de vida e práticas espirituais.',
    indications: 'Ansiedade, depressão, estresse, insônia, vícios, fobias, transtornos de humor, problemas de relacionamento e busca por desenvolvimento espiritual.',
    benefits: 'Equilíbrio mental e emocional, redução do estresse, melhora da clareza mental, fortalecimento da vontade, desenvolvimento espiritual e autoconhecimento.',
    contraindications: 'Transtornos psicóticos agudos, esquizofrenia em crise, dependência química severa e resistência extrema a práticas espirituais.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '27',
    name: 'Sei Shiatsu',
    definition: 'O Sei Shiatsu é uma modalidade específica de Shiatsu desenvolvida no Brasil que combina técnicas tradicionais japonesas com abordagens terapêuticas ocidentais. Esta prática utiliza pressão com os dedos, palmas das mãos, cotovelos e joelhos em pontos específicos do corpo (tsubos) ao longo dos meridianos de energia para promover o equilíbrio energético e a saúde. O Sei Shiatsu incorpora também movimentos de alongamento, mobilizações articulares e técnicas de respiração. É uma terapia que trabalha com a energia vital (Ki) do corpo, buscando desobstruir bloqueios energéticos e restaurar o fluxo natural da energia, promovendo relaxamento, alívio de dores e bem-estar geral.',
    origin: 'Desenvolvido no Brasil a partir das técnicas tradicionais de Shiatsu japonês, adaptado às necessidades locais. Foi incluído no SUS em 2018.',
    application: 'Aplicação de pressão em pontos específicos do corpo, alongamentos, mobilizações articulares e técnicas de respiração, realizada em tatame ou maca.',
    indications: 'Dores musculares, estresse, ansiedade, insônia, problemas digestivos, dores de cabeça, tensões corporais e desequilíbrios energéticos.',
    benefits: 'Alívio de dores e tensões, relaxamento profundo, melhora da circulação, equilíbrio energético, redução do estresse e promoção do bem-estar.',
    contraindications: 'Fraturas recentes, inflamações agudas, febre alta, problemas cardíacos graves, gravidez (alguns pontos) e câncer em áreas de aplicação.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '7',
    name: 'Musicoterapia',
    definition: 'Uso da música e seus elementos como ferramenta terapêutica para promover saúde física e mental.',
    origin: 'Utilizada desde a antiguidade com finalidades curativas, formalizada como terapia no século XX.',
    application: 'Envolve escutar, cantar, tocar instrumentos e criar música sob orientação de um musicoterapeuta.',
    indications: 'Transtornos de desenvolvimento, doenças neurológicas, depressão, ansiedade, autismo.',
    benefits: 'Redução do estresse, melhora da comunicação, estímulo cognitivo, expressão emocional.',
    contraindications: 'Não possui contraindicações específicas, mas deve ser adaptada às necessidades individuais.',
    imageUrl: 'https://sdmntprnorthcentralus.oaiusercontent.com/files/00000000-a568-622f-9f6a-2c42e2f57662/raw?se=2025-06-01T21%3A32%3A47Z&sp=r&sv=2024-08-04&sr=b&scid=05c78bc3-a8cf-5e7a-98aa-bef9a26c8339&skoid=add8ee7d-5fc7-451e-b06e-a82b2276cf62&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-06-01T03%3A46%3A22Z&ske=2025-06-02T03%3A46%3A22Z&sks=b&skv=2024-08-04&sig=2d9ZfAO3sRktC2AuYoCZ6N5RtwPwCKFUYnRhgX6Vhbs%3D',
  },
  {
    id: '8',
    name: 'Homeopatia',
    definition: 'Sistema terapêutico baseado no princípio da similitude, utilizando substâncias diluídas e dinamizadas.',
    origin: 'a homeopatia, sistema médico complexo de caráter holístico, é baseada no princípio vitalista e no uso da lei dos semelhantes, enunciada por Hipócrates no século iV a.C. Foi desenvolvida por samuel Hahnemann no século XViii. após estuos e reflexões baseados na observação clínica e em experimentos realizados na época, Hahnemann sistematizou os princípios filosóficos e doutrinários da homeopatia em suas obras Organon da Arte de Curar e Doenças Crônicas. a partir daí, essa racionalidade médica experimentou grande expansão por várias regiões do mundo, estando hoje firmemente implantada em diversos países da europa, das américas e da Ásia. no Brasil, a homeopatia foi introduzida por Benoit Mure em 1840, tornando-se nova opção de tratamento.',
    application: 'Utiliza medicamentos homeopáticos produzidos a partir de substâncias de origem vegetal, animal ou mineral, altamente diluídas.',
    indications: 'Diversas condições agudas e crônicas, tratando o indivíduo como um todo.',
    benefits: 'Tratamento individualizado, sem efeitos colaterais, estímulo à capacidade de autocura do organismo.',
    contraindications: 'Não substitui tratamentos convencionais em doenças graves ou emergências médicas.',
    imageUrl: 'https://sdmntprwestcentralus.oaiusercontent.com/files/00000000-268c-61fb-806c-3fac741e0170/raw?se=2025-06-01T21%3A34%3A35Z&sp=r&sv=2024-08-04&sr=b&scid=6c8df4b4-5cfb-58bd-a758-b801377b4d98&skoid=add8ee7d-5fc7-451e-b06e-a82b2276cf62&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-31T21%3A47%3A40Z&ske=2025-06-01T21%3A47%3A40Z&sks=b&skv=2024-08-04&sig=zlDEFVbhVRkBbHgyWQMA7DozX1/GpkBPQnFVq20CEtU%3D',
  },
  {
    id: '9',
    name: 'Terapia Comunitária Integrativa',
    definition: 'A Terapia Comunitária Integrativa (TCI) é uma prática terapêutica em grupo, de origem brasileira, que visa construir redes sociais solidárias, fortalecer os laços sociais e comunitários, e apoiar a saúde mental. Funciona como um espaço de acolhimento e partilha de experiências e sofrimentos, valorizando o saber popular.',
    origin: 'Foi criada em 1987 pelo psiquiatra, teólogo e antropólogo Adalberto de Paula Barreto, no Projeto Quatro Varas, na favela do Pirambu em Fortaleza, Ceará.',
    application: 'A TCI é realizada em rodas de conversa abertas à comunidade, com uma estrutura horizontal onde todos têm voz. Os encontros são conduzidos por terapeutas comunitários capacitados, seguindo etapas específicas que incluem o acolhimento, a escolha do tema a ser discutido a partir das preocupações dos participantes, a partilha de experiências e a busca coletiva por estratégias de superação.',
    indications: 'É indicada para pessoas que vivenciam sofrimento emocional, dificuldades de relacionamento, estresse, ansiedade, e para quem busca autoconhecimento e fortalecimento de vínculos. É um espaço para lidar com as inquietações do dia a dia.',
    benefits: 'Promove a melhora da autoestima, o desenvolvimento da autonomia e do empoderamento, o aumento da resiliência, o fortalecimento dos vínculos sociais e familiares, o alívio do sofrimento psíquico e a construção de um senso de pertencimento e comunidade.',
    contraindications: 'Não possui contraindicações específicas, sendo uma prática inclusiva. No entanto, não substitui tratamentos médicos ou psicológicos especializados quando necessários.',
    imageUrl: 'https://images.pexels.com/photos/7148894/pexels-photo-7148894.jpeg',
  },
  {
    id: '10',
    name: 'Shantala',
    definition: 'Shantala é uma técnica de massagem de origem indiana destinada a bebês (a partir de um mês de vida) e crianças, que utiliza movimentos suaves e repetitivos com óleo vegetal em diversas partes do corpo.',
    origin: 'É uma prática tradicional indiana, introduzida no Ocidente pelo obstetra francês Frédérick Leboyer, que a aprendeu com uma mulher indiana chamada Shantala.',
    application: 'A massagem é aplicada pela mãe, pai ou cuidador, com o bebê despido, em um ambiente tranquilo e aquecido. Utiliza-se óleo vegetal (como de amêndoas ou girassol) e os movimentos seguem uma sequência específica, abrangendo rosto, peito, braços, mãos, barriga, pernas, pés e costas. A sessão dura cerca de 10 a 30 minutos e pode ser feita diariamente.',
    indications: 'Indicada para bebês a partir de um mês de idade (após a queda do coto umbilical e cicatrização).',
    benefits: 'Fortalece o vínculo afetivo entre pais e filhos, alivia cólicas e prisão de ventre, melhora o sono, estimula o desenvolvimento psicomotor e sensorial, contribui para o ganho de peso em bebês prematuros, fortalece o sistema imunológico, melhora a circulação e a respiração, e pode reduzir os níveis de depressão e ansiedade nas mães.',
    contraindications: 'Não deve ser realizada se o bebê estiver com febre, gripado, com a pele irritada ou ferida, logo após a amamentação, se estiver dormindo, ou em casos de fraturas, hematomas, hérnias, doenças respiratórias ou cardíacas agudas, ou com o coto umbilical ainda presente. É fundamental que a técnica seja aplicada corretamente por alguém que tenha feito um curso.',
    imageUrl: 'https://images.pexels.com/photos/4473765/pexels-photo-4473765.jpeg',
  },
  {
    id: '11',
    name: 'Dança Circular',
    definition: 'Prática de dança em grupo, realizada em círculo, que promove a integração, a expressão corporal e o bem-estar.',
    origin: 'Resgata danças tradicionais de diversos povos e culturas, popularizada por Bernhard Wosien na década de 1970.',
    application: 'Movimentos simples e repetitivos, realizados em roda, ao som de músicas de diferentes origens.',
    indications: 'Estresse, ansiedade, isolamento social, baixa autoestima, busca por autoconhecimento.',
    benefits: 'Melhora da coordenação motora, aumento da consciência corporal, redução do estresse, fortalecimento de vínculos sociais e senso de comunidade.',
    contraindications: 'Limitações físicas severas que impeçam a participação nos movimentos. Geralmente adaptável.',
    imageUrl: 'https://images.pexels.com/photos/7080837/pexels-photo-7080837.jpeg', // Exemplo de URL
  },
  {
    id: '12',
    name: 'Biodança',
    definition: 'Sistema de integração humana, renovação orgânica e reaprendizagem das funções originárias da vida, através de vivências induzidas pela música e pelo movimento.',
    origin: 'Criada pelo psicólogo e antropólogo chileno Rolando Toro Araneda na década de 1960.',
    application: 'Sessões em grupo com exercícios e danças específicas, propostas pelo facilitador, com músicas selecionadas para induzir vivências integradoras.',
    indications: 'Estresse, depressão, ansiedade, dificuldades de relacionamento, busca por desenvolvimento pessoal e expressividade.',
    benefits: 'Aumento da vitalidade, melhora da autoestima e da comunicação, desenvolvimento da afetividade, integração corpo-mente.',
    contraindications: 'Algumas condições psiquiátricas agudas podem requerer avaliação prévia.',
    imageUrl: 'https://images.pexels.com/photos/317155/pexels-photo-317155.jpeg', // Exemplo de URL
  },
  {
    id: '13',
    name: 'Constelação Familiar',
    definition: 'Abordagem terapêutica sistêmica que busca identificar e solucionar emaranhamentos em sistemas familiares que podem estar causando sofrimento.',
    origin: 'Desenvolvida pelo psicoterapeuta alemão Bert Hellinger.',
    application: 'Pode ser realizada em grupo, com representantes, ou individualmente. O facilitador ajuda a visualizar a dinâmica familiar e encontrar um novo equilíbrio.',
    indications: 'Conflitos familiares, dificuldades de relacionamento, padrões repetitivos de comportamento, doenças sem causa orgânica aparente.',
    benefits: 'Compreensão das dinâmicas familiares, liberação de padrões inconscientes, reconciliação e maior harmonia nos relacionamentos.',
    contraindications: 'Não é recomendada como única forma de tratamento para transtornos psiquiátricos graves. Importante buscar profissionais qualificados.',
    imageUrl: 'https://images.pexels.com/photos/5699475/pexels-photo-5699475.jpeg', // Exemplo de URL
  },
  {
    id: '14',
    name: 'Ozonioterapia',
    definition: 'A Ozonioterapia é uma prática terapêutica que utiliza a aplicação de uma mistura de gases oxigênio e ozônio (ozônio medicinal) por diversas vias, com finalidade terapêutica.',
    origin: 'O ozônio foi descoberto em 1840. Durante a Primeira Guerra Mundial, foi utilizado para tratar feridas de soldados. No Brasil, o uso experimental começou na década de 1980 e a prática foi regulamentada para algumas áreas a partir de 2015.',
    application: 'Pode ser aplicada de diversas formas: cutânea (água ou óleo ozonizado), bucal (bochechos), retal (insuflação), subcutânea, intramuscular, intravenosa (auto-hemoterapia maior ou menor – esta última controversa e com restrições).',
    indications: 'A ANVISA aprova seu uso para fins odontológicos (tratamento de cáries, periodontite, cirurgias) e estéticos (celulite, gordura localizada). Outras indicações médicas são controversas e carecem de comprovação científica robusta, embora uma lei recente (Lei nº 14.648/2023) autorize seu uso como tratamento complementar em todo o território nacional.',
    benefits: 'Potenciais benefícios incluem melhora da oxigenação dos tecidos, fortalecimento do sistema imunológico, ação anti-inflamatória, analgésica e antisséptica, e estímulo à cicatrização.',
    contraindications: 'Deficiência da enzima G6PD (favismo), gravidez e lactação (por falta de estudos), infarto agudo do miocárdio recente, hipertireoidismo não controlado, intoxicação alcoólica aguda, problemas de coagulação sanguínea ou hemorragias ativas.',
    imageUrl: 'https://images.pexels.com/photos/7615467/pexels-photo-7615467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', // Exemplo de URL, idealmente uma imagem representativa da Ozonioterapia
  },
  {
    id: '15',
    name: 'Reflexoterapia',
    definition: 'A Reflexoterapia é uma técnica terapêutica não invasiva que se baseia na aplicação de pressão em pontos específicos (plexos nervosos) localizados nos pés, mãos, orelhas, e face, que correspondem a diferentes órgãos e partes do corpo.',
    origin: 'Evidências de práticas semelhantes remontam a antigas civilizações na Índia, China e Egito (cerca de 2330 a.C.). No Ocidente, foi popularizada no início do século XX pelo Dr. William H. Fitzgerald (terapia zonal) e posteriormente desenvolvida por Eunice D. Ingham, considerada a "mãe da reflexologia moderna".',
    application: 'O reflexoterapeuta utiliza os dedos, principalmente o polegar, para aplicar pressão em pontos reflexos. A reflexoterapia podal (nos pés) é a mais comum. A pressão estimula o sistema nervoso, promovendo o equilíbrio energético e a capacidade de autocura do corpo.',
    indications: 'É indicada para aliviar o estresse, ansiedade, depressão, dores de cabeça e enxaquecas, insônia, dores musculares e articulares, problemas circulatórios e hormonais, e melhorar o funcionamento geral do organismo.',
    benefits: 'Proporciona relaxamento profundo, bem-estar físico e mental, melhora da circulação sanguínea e linfática, fortalecimento do sistema imunológico, alívio da dor, e estímulo das funções corporais.',
    contraindications: 'Primeiro trimestre da gravidez, inflamações linfáticas agudas, trombose venosa profunda, ferimentos ou infecções nos pés (para reflexoterapia podal), câncer de pele nos locais de aplicação, aneurisma, leucemia, febre alta, doenças infecciosas agudas, e insuficiência cardíaca congestiva. Cautela em casos de gangrena, micose extensa, eczema ou dermatite intensa nos pés, crise aguda de doenças reumáticas ou psicoses.',
    imageUrl: 'https://images.pexels.com/photos/4506079/pexels-photo-4506079.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', // Exemplo de URL
  },
  {
    id: '16',
    name: 'Termalismo Social/Crenoterapia',
    definition: 'O Termalismo Social ou Crenoterapia é uma prática terapêutica que utiliza as propriedades de águas minerais naturais (termais ou não), gases e peloides (lamas) para fins de prevenção, tratamento e manutenção da saúde.',
    origin: 'O uso de águas termais para fins terapêuticos remonta à antiguidade (gregos e romanos). O termo "Termalismo Social" surgiu no Brasil na década de 1950, visando o acesso mais amplo a esses recursos.',
    application: 'As técnicas incluem banhos de imersão, ingestão de água mineral (hidropinia), inalações, vaporizações, aplicação de peloides, entre outras, realizadas em estâncias termais ou balneários.',
    indications: 'Problemas dermatológicos (psoríase, eczema), reumatológicos (artrite, artrose), respiratórios (asma, bronquite), gastrointestinais, circulatórios, além de estresse e busca por relaxamento e bem-estar.',
    benefits: 'As águas minerais podem ter efeitos anti-inflamatórios, analgésicos, relaxantes musculares, cicatrizantes, e estimulantes do sistema imunológico, dependendo de sua composição química.',
    contraindications: 'Doenças cardíacas descompensadas, hipertensão arterial grave não controlada, infecções agudas, febre, certas condições de pele em fase aguda (ex: feridas abertas), e tumores malignos ativos. É importante avaliação médica prévia.',
    imageUrl: 'https://images.pexels.com/photos/1420000/pexels-photo-1420000.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', // Exemplo de URL
  },
  {
    id: '17',
    name: 'Shantala',
    definition: 'A Shantala é uma técnica de massagem para bebês originária da Índia, que promove o vínculo afetivo entre pais e filhos através do toque terapêutico. Esta prática milenar utiliza movimentos suaves e ritmados aplicados no corpo do bebê, proporcionando relaxamento, alívio de cólicas, melhora do sono e fortalecimento do sistema imunológico. A Shantala vai além da técnica de massagem, sendo um momento de comunicação não-verbal, amor e cuidado que contribui para o desenvolvimento neuropsicomotor da criança. É uma prática que pode ser facilmente aprendida pelos pais e cuidadores, criando momentos especiais de conexão e bem-estar para toda a família.',
    origin: 'Prática milenar originária da Índia, popularizada no Ocidente pelo obstetra francês Frédérick Leboyer na década de 1970. Foi incluída no SUS em 2017.',
    application: 'Massagem suave aplicada pelos pais ou cuidadores no bebê, utilizando movimentos específicos nas pernas, abdômen, peito, braços, rosto e costas, preferencialmente em ambiente aquecido e tranquilo.',
    indications: 'Cólicas do bebê, agitação e irritabilidade, dificuldades de sono, constipação intestinal, fortalecimento do vínculo pais-bebê, estimulação do desenvolvimento neuropsicomotor e relaxamento.',
    benefits: 'Alívio de cólicas e gases, melhora da qualidade do sono, fortalecimento do vínculo afetivo, estímulo da circulação sanguínea, desenvolvimento neuropsicomotor, redução do estresse do bebê e dos pais.',
    contraindications: 'Febre, infecções de pele, feridas abertas, fraturas, problemas cardíacos congênitos graves e recusa persistente do bebê.',
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg',
  },
  {
    id: '18',
    name: 'Terapia Comunitária Integrativa',
    definition: 'A Terapia Comunitária Integrativa (TCI) é uma prática de cuidado coletivo que busca promover a saúde mental e o fortalecimento de vínculos comunitários através de rodas de conversa estruturadas. Desenvolvida no Ceará, esta abordagem utiliza a sabedoria popular, a cultura local e a rede de apoio social como recursos terapêuticos. A TCI cria um espaço horizontal de escuta, acolhimento e partilha de experiências, onde os participantes podem expressar seus sofrimentos e encontrar soluções coletivas. É uma metodologia que valoriza a resiliência comunitária, promove a inclusão social e fortalece a identidade cultural, contribuindo para a prevenção de agravos psicossociais.',
    origin: 'Desenvolvida pelo psiquiatra Adalberto Barreto no Ceará na década de 1980. Foi incluída no SUS em 2017 como prática integrativa.',
    application: 'Rodas de conversa comunitárias conduzidas por terapeuta comunitário capacitado, seguindo metodologia específica com etapas de acolhimento, escolha do tema, contextualização, problematização e encerramento.',
    indications: 'Sofrimento psíquico, isolamento social, conflitos familiares, luto, desemprego, violência doméstica, dependência química, depressão, ansiedade e necessidade de fortalecimento comunitário.',
    benefits: 'Fortalecimento de vínculos sociais, redução do isolamento, melhora da autoestima, desenvolvimento de estratégias de enfrentamento, valorização da cultura local, prevenção de agravos psicossociais e promoção da cidadania.',
    contraindications: 'Surtos psicóticos agudos, ideação suicida ativa, intoxicação por substâncias, transtornos que impeçam a participação em grupo e resistência extrema à exposição em grupo.',
    imageUrl: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg',
  },
  {
    id: '19',
    name: 'Terapia de Florais',
    definition: 'A Terapia de Florais é um sistema terapêutico que utiliza essências florais para tratar desequilíbrios emocionais e promover o bem-estar mental. Desenvolvida pelo médico inglês Edward Bach, esta prática baseia-se no princípio de que as flores possuem frequências vibracionais que podem harmonizar estados emocionais negativos e restaurar o equilíbrio interior. Os florais são preparados através da infusão solar ou fervura de flores em água pura, capturando a "assinatura energética" da planta. Existem diversos sistemas florais além dos Florais de Bach, como os Florais de Minas, Californianos, Australianos, entre outros. É uma terapia suave, sem efeitos colaterais, que pode ser utilizada por pessoas de todas as idades.',
    origin: 'Desenvolvida pelo médico inglês Edward Bach na década de 1930. Foi incluída no SUS em 2018 como prática integrativa.',
    application: 'Prescrição individualizada de essências florais após consulta detalhada, administradas via oral em gotas, podendo ser combinadas conforme necessidades emocionais específicas.',
    indications: 'Ansiedade, depressão, medos, traumas emocionais, baixa autoestima, estresse, insônia, irritabilidade, luto, dificuldades de relacionamento e desequilíbrios emocionais diversos.',
    benefits: 'Equilíbrio emocional, redução da ansiedade e estresse, melhora da autoestima, maior clareza mental, harmonização de conflitos internos, desenvolvimento pessoal e bem-estar emocional.',
    contraindications: 'Não há contraindicações absolutas. É uma terapia segura que pode ser utilizada por pessoas de todas as idades, incluindo gestantes, crianças e idosos.',
    imageUrl: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  },
  {
    id: '20',
    name: 'Yoga',
    definition: 'O Yoga é uma prática originária da Índia há cerca de 5 mil anos, concebida como uma disciplina espiritual que visa a evolução do ser humano em todos os aspectos: físico, mental, emocional e espiritual. A palavra "yoga" tem origem no sânscrito "yuj", que significa "unir" ou "integrar", refletindo a ideia de união e reintegração do corpo com a mente para alcançar o equilíbrio e um estado elevado de existência. O Yoga combina posturas físicas (asanas), técnicas de respiração (pranayama), meditação e princípios filosóficos para promover saúde, bem-estar e autoconhecimento. Existem diversos estilos de yoga, desde os mais suaves até os mais dinâmicos, adaptando-se às necessidades e limitações de cada praticante.',
    origin: 'Surgiu na Índia há aproximadamente 5.000 anos, documentado nos textos sagrados Vedas. Foi incluído no SUS em 2017.',
    application: 'Prática de posturas físicas (asanas), exercícios de respiração (pranayama) e meditação, podendo ser realizada individualmente ou em grupos, com orientação de instrutor qualificado.',
    indications: 'Estresse, ansiedade, depressão, insônia, dores crônicas, hipertensão, problemas posturais, falta de flexibilidade, desequilíbrios emocionais e busca por autoconhecimento.',
    benefits: 'Melhora da flexibilidade e força muscular, redução do estresse e ansiedade, melhora da qualidade do sono, equilíbrio emocional, aumento da concentração, fortalecimento do sistema imunológico e promoção do autoconhecimento.',
    contraindications: 'Não há contraindicações absolutas, mas algumas posturas podem ser contraindicadas para gestantes, pessoas com hérnia de disco, lesões específicas ou problemas cardíacos graves. A prática deve ser adaptada às limitações individuais.',
    imageUrl: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
  }
];

// Simulate API calls
export const getPractices = async (): Promise<Practice[]> => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return mockPractices;
};

export const getPracticeById = async (id: string): Promise<Practice> => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  
  const practice = mockPractices.find(practice => practice.id === id);
  
  if (!practice) {
    throw new Error('Practice not found');
  }
  
  return practice;
};